[pytest]
asyncio_mode = auto
addopts = -v
env =
    ENVIRONMENT=test
    DATABASE_URL=sqlite+aiosqlite:///./test.db
    CELERY_ALWAYS_EAGER=True
    MONNIFY_API_KEY=test_api_key
    MONNIFY_SECRET_KEY=test_secret_key
    MONNIFY_BASE_URL=https://sandbox.monnify.com
